# Generated by Django 3.1.5 on 2021-01-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_interview_preparation'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
