# Generated by Django 3.1.5 on 2021-02-02 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_auto_20210202_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preparation',
            name='topic',
        ),
    ]
