# Generated by Django 3.1.5 on 2021-02-02 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_remove_preparation_topic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
